filenameTemplate: "[{rel_group}] {title} - {ep_num} [{suffix}]"
releaseGroup: CR
epNumLength: 2
fileSuffix: SIZEp
videoQuality: 1080p
dubLanguage: jpn
mp4mux: false
muxSubs: false
noCleanUp: false
kStream: 1
nServer: 1
tsparts: 20
oldStreams: false
oldSubs: false
hsLang: arME
dlSubs: arME
useBCPtags: false
defSubLang: none
useFolder: true
proxy: false
proxy_auth: false
proxy_ssp: false
